-- DOCUMENTATION ONLY. This file records a production ledger row.
-- It is not a functional change. Do not re-apply this name.
--
-- Production (eigfvribtntbxyjutsma) already has:
--   supabase_migrations.schema_migrations
--     version = 20260911223101
--     name    = synastry_post_em_dash_keep_links
--
-- Two agents applied nearly identical body rewrites 53 seconds apart:
--   20260911223101  synastry_post_em_dash_keep_links
--   20260911223154  synastry_post_strip_reintroduced_em_dash
--
-- The payloads were the same dash-free markdown (three internal links
-- kept). Last writer of public.posts.body is
-- synastry_post_strip_reintroduced_em_dash, so that file is the source of
-- truth for the live body. This name stays in the repo only so Migration
-- Ledger Parity can match the ledger row (ENGINEERING.md §16). Deleting
-- the ledger row is forbidden. Leaving the original UPDATE here would
-- invert last-writer on filename-ordered replay (this file is 233000,
-- strip is 230000).
--
-- The original apply also set read_time_minutes = 6 because
-- computeReadTimeMinutes used to count each U+2014 as a word. That
-- formula is fixed in apps/web/lib/blog.ts; the live row follows the
-- corrected estimate. This comment-only file does not write the row.
